name: Playwright Docker Test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Set up Docker Compose
        run: |
          docker compose up -d

      - name: Run Playwright Tests
        run: |
          echo "Waiting for services to be ready..."
          until curl --output /dev/null --silent --head --fail http://localhost:5000/todos; do
            printf '.'
            sleep 5
          done
          echo "Services are ready. Running tests..."
          npm run test

      - name: Upload Screenshot
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshot
          path: error-screenshot.png

      - name: Get Docker logs
        if: always()
        run: |
          docker logs testing-playground-backend-1 > backend_logs.txt || echo "No logs available"
          docker logs testing-playground-frontend-1 > frontend_logs.txt || echo "No logs available"
          docker logs testing-playground-db-1 > db_logs.txt || echo "No logs available"

      - name: Upload Docker logs（frontend）
        uses: actions/upload-artifact@v4
        with:
          name: frontend-logs
          path: frontend_logs.txt

      - name: Upload Docker logs（backend）
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-logs
          path: backend_logs.txt

      - name: Upload Docker logs（db）
        uses: actions/upload-artifact@v4
        with:
          name: db-logs
          path: db_logs.txt

      - name: Shutdown Docker Compose
        if: always()
        run: |
          docker compose down
